export enum EShipPeriodQueryKey {
  ALL = 'ALL',
  WAITING_TO_RECEIVE = 'WAITING_TO_RECEIVE',
  CREATED = 'CREATED',
  REGISTERED = 'REGISTERED',
  IN_TRANSIT = 'IN_TRANSIT',
  IN_DESTINATION = 'IN_DESTINATION',
  DELIVERED = 'DELIVERED',
}
